"""initial schema

Revision ID: 10a05e93d21f
Revises:
Create Date: 2026-03-23 15:41:12.308228
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.core.db import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = "10a05e93d21f"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("parser_key", sa.String(length=80), nullable=False),
        sa.Column("base_url", sa.String(length=255), nullable=False),
        sa.Column("start_url", sa.String(length=255), nullable=False),
        sa.Column("schedule_enabled", sa.Boolean(), nullable=False),
        sa.Column("schedule_interval_minutes", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("health_status", sa.String(length=32), nullable=False),
        sa.Column("last_run_started_at", UTCDateTime(), nullable=True),
        sa.Column("last_run_finished_at", UTCDateTime(), nullable=True),
        sa.Column("last_successful_run_at", UTCDateTime(), nullable=True),
        sa.Column("last_failed_run_at", UTCDateTime(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sources_slug"), ["slug"], unique=True)

    op.create_table(
        "telegram_chats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("chat_type", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("telegram_chats", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_telegram_chats_telegram_chat_id"), ["telegram_chat_id"], unique=True
        )

    op.create_table(
        "telegram_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("telegram_users", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_telegram_users_telegram_user_id"), ["telegram_user_id"], unique=True
        )

    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("source_item_key", sa.String(length=255), nullable=False),
        sa.Column("canonical_url", sa.String(length=500), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("currency", sa.String(length=16), nullable=False),
        sa.Column("price_amount", sa.Float(), nullable=True),
        sa.Column("availability_status", sa.String(length=32), nullable=False),
        sa.Column("rating", sa.String(length=32), nullable=True),
        sa.Column("attributes_json", sa.JSON(), nullable=False),
        sa.Column("comparison_hash", sa.String(length=64), nullable=False),
        sa.Column("first_seen_at", UTCDateTime(), nullable=False),
        sa.Column("last_seen_at", UTCDateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("missing_run_count", sa.Integer(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "source_item_key", name="uq_source_item_key"),
    )
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_items_source_id"), ["source_id"], unique=False)

    op.create_table(
        "monitor_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_user_id", sa.Integer(), nullable=False),
        sa.Column("telegram_chat_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("category", sa.String(length=255), nullable=True),
        sa.Column("min_price", sa.Float(), nullable=True),
        sa.Column("max_price", sa.Float(), nullable=True),
        sa.Column("include_keywords_json", sa.JSON(), nullable=False),
        sa.Column("exclude_keywords_json", sa.JSON(), nullable=False),
        sa.Column("instant_alerts_enabled", sa.Boolean(), nullable=False),
        sa.Column("digest_enabled", sa.Boolean(), nullable=False),
        sa.Column("priority_mode", sa.String(length=32), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["telegram_chat_id"],
            ["telegram_chats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["telegram_user_id"],
            ["telegram_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("monitor_profiles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_monitor_profiles_source_id"), ["source_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_monitor_profiles_telegram_chat_id"), ["telegram_chat_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_monitor_profiles_telegram_user_id"), ["telegram_user_id"], unique=False
        )

    op.create_table(
        "monitoring_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("trigger_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", UTCDateTime(), nullable=False),
        sa.Column("finished_at", UTCDateTime(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("pages_fetched", sa.Integer(), nullable=False),
        sa.Column("items_parsed", sa.Integer(), nullable=False),
        sa.Column("new_items_count", sa.Integer(), nullable=False),
        sa.Column("changed_items_count", sa.Integer(), nullable=False),
        sa.Column("removed_items_count", sa.Integer(), nullable=False),
        sa.Column("events_count", sa.Integer(), nullable=False),
        sa.Column("alerts_sent_count", sa.Integer(), nullable=False),
        sa.Column("parse_completeness_ratio", sa.Float(), nullable=True),
        sa.Column("health_evaluation", sa.String(length=32), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("monitoring_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_monitoring_runs_source_id"), ["source_id"], unique=False
        )

    op.create_table(
        "ai_summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.String(length=120), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("highlights_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("response_json", sa.JSON(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["monitoring_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ai_summaries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ai_summaries_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ai_summaries_source_id"), ["source_id"], unique=False)

    op.create_table(
        "detected_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("dedupe_key", sa.String(length=255), nullable=False),
        sa.Column("old_value_json", sa.JSON(), nullable=True),
        sa.Column("new_value_json", sa.JSON(), nullable=True),
        sa.Column("changed_fields_json", sa.JSON(), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=False),
        sa.Column("is_suppressed", sa.Boolean(), nullable=False),
        sa.Column("suppressed_reason", sa.String(length=120), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["monitoring_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("detected_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_detected_events_dedupe_key"), ["dedupe_key"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_detected_events_item_id"), ["item_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_detected_events_run_id"), ["run_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_detected_events_source_id"), ["source_id"], unique=False
        )

    op.create_table(
        "item_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("currency", sa.String(length=16), nullable=False),
        sa.Column("price_amount", sa.Float(), nullable=True),
        sa.Column("availability_status", sa.String(length=32), nullable=False),
        sa.Column("rating", sa.String(length=32), nullable=True),
        sa.Column("attributes_json", sa.JSON(), nullable=False),
        sa.Column("comparison_hash", sa.String(length=64), nullable=False),
        sa.Column("observed_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["monitoring_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("item_snapshots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_item_snapshots_item_id"), ["item_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_item_snapshots_run_id"), ["run_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_item_snapshots_source_id"), ["source_id"], unique=False
        )

    op.create_table(
        "monitor_matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("monitor_profile_id", sa.Integer(), nullable=False),
        sa.Column("detected_event_id", sa.Integer(), nullable=False),
        sa.Column("monitoring_run_id", sa.Integer(), nullable=False),
        sa.Column("matched", sa.Boolean(), nullable=False),
        sa.Column("match_reason", sa.Text(), nullable=False),
        sa.Column("priority", sa.String(length=16), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["detected_event_id"],
            ["detected_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["monitor_profile_id"],
            ["monitor_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["monitoring_run_id"],
            ["monitoring_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("monitor_matches", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_monitor_matches_detected_event_id"), ["detected_event_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_monitor_matches_monitor_profile_id"),
            ["monitor_profile_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_monitor_matches_monitoring_run_id"), ["monitoring_run_id"], unique=False
        )

    op.create_table(
        "notification_deliveries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("monitor_profile_id", sa.Integer(), nullable=False),
        sa.Column("telegram_chat_id", sa.Integer(), nullable=False),
        sa.Column("detected_event_id", sa.Integer(), nullable=True),
        sa.Column("monitoring_run_id", sa.Integer(), nullable=True),
        sa.Column("delivery_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("message_preview", sa.Text(), nullable=True),
        sa.Column("telegram_message_id", sa.String(length=120), nullable=True),
        sa.Column("error_text", sa.Text(), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("sent_at", UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["detected_event_id"],
            ["detected_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["monitor_profile_id"],
            ["monitor_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["monitoring_run_id"],
            ["monitoring_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["telegram_chat_id"],
            ["telegram_chats.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notification_deliveries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notification_deliveries_detected_event_id"),
            ["detected_event_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_notification_deliveries_monitor_profile_id"),
            ["monitor_profile_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_notification_deliveries_monitoring_run_id"),
            ["monitoring_run_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_notification_deliveries_telegram_chat_id"),
            ["telegram_chat_id"],
            unique=False,
        )

    op.create_table(
        "notification_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=False),
        sa.Column("notification_type", sa.String(length=32), nullable=False),
        sa.Column("destination", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("provider_message_id", sa.String(length=120), nullable=True),
        sa.Column("payload_preview", sa.Text(), nullable=True),
        sa.Column("sent_at", UTCDateTime(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["detected_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["monitoring_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notification_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notification_logs_event_id"), ["event_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_notification_logs_run_id"), ["run_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_notification_logs_source_id"), ["source_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_logs_source_id"))
        batch_op.drop_index(batch_op.f("ix_notification_logs_run_id"))
        batch_op.drop_index(batch_op.f("ix_notification_logs_event_id"))

    op.drop_table("notification_logs")
    with op.batch_alter_table("notification_deliveries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_deliveries_telegram_chat_id"))
        batch_op.drop_index(batch_op.f("ix_notification_deliveries_monitoring_run_id"))
        batch_op.drop_index(batch_op.f("ix_notification_deliveries_monitor_profile_id"))
        batch_op.drop_index(batch_op.f("ix_notification_deliveries_detected_event_id"))

    op.drop_table("notification_deliveries")
    with op.batch_alter_table("monitor_matches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_monitor_matches_monitoring_run_id"))
        batch_op.drop_index(batch_op.f("ix_monitor_matches_monitor_profile_id"))
        batch_op.drop_index(batch_op.f("ix_monitor_matches_detected_event_id"))

    op.drop_table("monitor_matches")
    with op.batch_alter_table("item_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_item_snapshots_source_id"))
        batch_op.drop_index(batch_op.f("ix_item_snapshots_run_id"))
        batch_op.drop_index(batch_op.f("ix_item_snapshots_item_id"))

    op.drop_table("item_snapshots")
    with op.batch_alter_table("detected_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_detected_events_source_id"))
        batch_op.drop_index(batch_op.f("ix_detected_events_run_id"))
        batch_op.drop_index(batch_op.f("ix_detected_events_item_id"))
        batch_op.drop_index(batch_op.f("ix_detected_events_dedupe_key"))

    op.drop_table("detected_events")
    with op.batch_alter_table("ai_summaries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_summaries_source_id"))
        batch_op.drop_index(batch_op.f("ix_ai_summaries_run_id"))

    op.drop_table("ai_summaries")
    with op.batch_alter_table("monitoring_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_monitoring_runs_source_id"))

    op.drop_table("monitoring_runs")
    with op.batch_alter_table("monitor_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_monitor_profiles_telegram_user_id"))
        batch_op.drop_index(batch_op.f("ix_monitor_profiles_telegram_chat_id"))
        batch_op.drop_index(batch_op.f("ix_monitor_profiles_source_id"))

    op.drop_table("monitor_profiles")
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_items_source_id"))

    op.drop_table("items")
    with op.batch_alter_table("telegram_users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_telegram_users_telegram_user_id"))

    op.drop_table("telegram_users")
    with op.batch_alter_table("telegram_chats", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_telegram_chats_telegram_chat_id"))

    op.drop_table("telegram_chats")
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sources_slug"))

    op.drop_table("sources")
    # ### end Alembic commands ###
